shfSecurity:
  index:
    security: false
  login:
    security: false
  logout:
    security: true
  noPermission:
    security: false
  exception:
    security: false

usuario:
  index:
    security: true
    credentials:
      - [admin, usuario]
  insert:
    security: true
  edit:
    security: true
