<?php
use mvc\session\sessionClass as session ?>

shfSecurity:
  index:
    security: false
  login:
    security: false
  logout:
    security: true
  noPermission:
    security: false
  exception:
    security: false
    
##------------------Categoria ------------------------------##    
categoria:
  index:
    security: true
    credentials:
      - [admin]
    
  insert:
    security: true
    credentials:
      - [admin]
      
  edit:
    security: true
    credentials:
      - [admin]
      
##------------------------Credencial--------------------------##      
    
credencial:
  index:
    security: true
    credentials:
      - [admin]
      
      
  insert:
    security: true
    credentials:
      - [admin]
      
  edit:
    security: true 
    credentials:
      - [admin]
      
##------------------------Dato Usuario ------------------------##      
    
datoUsuario:
  index:
    security: true
    credentials:
      - [admin]
  
  insert:
    security: false
   
   
  edit:
    security: false 
   
  
  
##---------------------------Bitacora-------------------------##    
    
bitacora:
  index:
    security: true
    credentials:
      - [admin]
   
##------------------------Evento --------------------------------##   
 
evento:
  index:
    security: true
    credentials:
      - [admin]
    
  insert:
    security: true
    
  edit:
    security: true 
##-----------------------Evento Patrocinador --------------------##    

eventoPatrocinador:
  index:
    security: true
    credentials:
      - [admin]
    
  insert:
    security: true
    credentials:
      - [admin]
    
  edit:
    security: true 
    credentials:
      - [admin]
    
##--------------------------Localidad ----------------------------------##

localidad:
  index:
    security: true
    credentials:
      - [admin]
    
  insert:
    security: true
    credentials:
      - [admin]
    
  edit:
    security: true 
    credentials:
      - [admin]
    
##---------------------------Organizacion -----------------------------##    
organizacion:
  index:
    security: true
    credentials:
      - [admin]
    
  insert:
    security: true
    credentials:
      - [admin]
    
  edit:
    security: true 
    credentials:
      - [admin]
    
##-----------------------------Patrocinador ----------------------------##    
    
patrocinador:
  index:
    security: true
    credentials:
      - [admin]
    
  insert:
    security: true
    credentials:
      - [admin]
    
  edit:
    security: true  
    credentials:
      - [admin]
    
##---------------------------Pqrs---------------------------------------##

pqrs:
  index:
    security: true
    credentials:
      - [admin]
    
  insert:
    security: true
    
  edit:
    security: true  
    
##--------------------------Tipo Documento -------------------------------##    
    
tipoDocumento:
  index:
    security: true
    credentials:
      - [admin]
    
  insert:
    security: true
    credentials:
      - [admin]
    
  edit:
    security: true 
    credentials:
      - [admin]
    
##---------------------------Tipo Pqrs --------------------------------##    
tipoPqrs:
  index:
    security: true
    credentials:
      - [admin]
    
  insert:
    security: true
    
  edit:
    security: true  
    


##-------------------------Usuario -----------------------------------##

usuario:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
      
  edit:
    security: true
    credentials:
      - [admin]
    
##-----------------------Usuario Credencial -------------------------##

usuarioCredencial:
  index:
    security: true
    credentials:
      - [admin]
    
  insert:
    security: true
    credentials:
      - [admin]
    
  edit:
    security: true
    credentials:
      - [admin]
##---------------------Usuario Gusta Categoria -----------------------##

usuarioGustaCategoria:
  index:
    security: true
    credentials:
      - [admin]
    
  insert:
    security: true
    credentials:
      - [admin]
    
  edit:
    security: true  
    credentials:
      - [admin]
      
##---------------------Reporte -----------------------##

reporte:
  index:
    security: true
    credentials:
      - [admin]
    
      