--
-- PostgreSQL database dump
--

-- Dumped from database version 9.3.5
-- Dumped by pg_dump version 9.3.5
-- Started on 2015-05-04 09:43:10 COT

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

--
-- TOC entry 213 (class 3079 OID 11829)
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- TOC entry 2287 (class 0 OID 0)
-- Dependencies: 213
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET search_path = public, pg_catalog;

--
-- TOC entry 176 (class 1259 OID 20821)
-- Name: bitacora_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE bitacora_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.bitacora_id_seq OWNER TO postgres;

--
-- TOC entry 2288 (class 0 OID 0)
-- Dependencies: 176
-- Name: SEQUENCE bitacora_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE bitacora_id_seq IS 'DbWrench Autogenerated Sequence.';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 207 (class 1259 OID 21180)
-- Name: bitacora; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE bitacora (
    id bigint DEFAULT nextval('bitacora_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    accion character varying(80) NOT NULL,
    tabla character varying(80) NOT NULL,
    registro bigint,
    observacion character varying(1024),
    fecha timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.bitacora OWNER TO postgres;

--
-- TOC entry 177 (class 1259 OID 20823)
-- Name: categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.categoria_id_seq OWNER TO postgres;

--
-- TOC entry 2289 (class 0 OID 0)
-- Dependencies: 177
-- Name: SEQUENCE categoria_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE categoria_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 190 (class 1259 OID 20857)
-- Name: categoria; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE categoria (
    id bigint DEFAULT nextval('categoria_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(45) NOT NULL
);


ALTER TABLE public.categoria OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 39767)
-- Name: clasificado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE clasificado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.clasificado_id_seq OWNER TO postgres;

--
-- TOC entry 2290 (class 0 OID 0)
-- Dependencies: 212
-- Name: SEQUENCE clasificado_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE clasificado_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 205 (class 1259 OID 21176)
-- Name: credencial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE credencial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.credencial_id_seq OWNER TO postgres;

--
-- TOC entry 2291 (class 0 OID 0)
-- Dependencies: 205
-- Name: SEQUENCE credencial_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE credencial_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 208 (class 1259 OID 21192)
-- Name: credencial; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE credencial (
    id bigint DEFAULT nextval('credencial_id_seq'::regclass) NOT NULL,
    nombre character varying(80) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


ALTER TABLE public.credencial OWNER TO postgres;

--
-- TOC entry 178 (class 1259 OID 20825)
-- Name: dato_usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE dato_usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.dato_usuario_id_seq OWNER TO postgres;

--
-- TOC entry 2292 (class 0 OID 0)
-- Dependencies: 178
-- Name: SEQUENCE dato_usuario_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE dato_usuario_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 191 (class 1259 OID 20873)
-- Name: dato_usuario; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE dato_usuario (
    id bigint DEFAULT nextval('dato_usuario_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(45) NOT NULL,
    apellido character varying(45) NOT NULL,
    correo character varying(70) NOT NULL,
    fecha_nacimiento date NOT NULL,
    localidad_id bigint NOT NULL,
    tipo_documento_id bigint NOT NULL,
    organizacion_id bigint,
    genero boolean,
    usuario_id bigint
);


ALTER TABLE public.dato_usuario OWNER TO postgres;

--
-- TOC entry 170 (class 1259 OID 20809)
-- Name: detalle_pqrs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE detalle_pqrs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.detalle_pqrs_id_seq OWNER TO postgres;

--
-- TOC entry 2293 (class 0 OID 0)
-- Dependencies: 170
-- Name: SEQUENCE detalle_pqrs_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE detalle_pqrs_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 192 (class 1259 OID 20885)
-- Name: detalle_pqrs; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE detalle_pqrs (
    id bigint DEFAULT nextval('detalle_pqrs_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    respuesta character varying(2048) NOT NULL,
    pqrs_id bigint,
    usuario_id bigint
);


ALTER TABLE public.detalle_pqrs OWNER TO postgres;

--
-- TOC entry 171 (class 1259 OID 20811)
-- Name: estado_pqrs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE estado_pqrs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.estado_pqrs_id_seq OWNER TO postgres;

--
-- TOC entry 2294 (class 0 OID 0)
-- Dependencies: 171
-- Name: SEQUENCE estado_pqrs_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE estado_pqrs_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 193 (class 1259 OID 20898)
-- Name: estado_pqrs; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE estado_pqrs (
    id bigint DEFAULT nextval('estado_pqrs_id_seq'::regclass) NOT NULL,
    nombre character varying(50) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


ALTER TABLE public.estado_pqrs OWNER TO postgres;

--
-- TOC entry 2295 (class 0 OID 0)
-- Dependencies: 193
-- Name: COLUMN estado_pqrs.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN estado_pqrs.actived IS 'TRUE activado ; FALSE desactivado';


--
-- TOC entry 179 (class 1259 OID 20827)
-- Name: evento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE evento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.evento_id_seq OWNER TO postgres;

--
-- TOC entry 2296 (class 0 OID 0)
-- Dependencies: 179
-- Name: SEQUENCE evento_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE evento_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 194 (class 1259 OID 20907)
-- Name: evento; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE evento (
    id bigint DEFAULT nextval('evento_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    imagen character varying(37),
    nombre character varying(45) NOT NULL,
    descripcion character varying(1024) NOT NULL,
    fecha_inicial_evento timestamp without time zone NOT NULL,
    fecha_final_evento timestamp without time zone NOT NULL,
    lugar_latitud character varying(100) NOT NULL,
    lugar_longitud character varying(100) NOT NULL,
    direccion character varying(150) NOT NULL,
    costo integer DEFAULT 0,
    categoria_id bigint,
    fecha_inicial_publicacion timestamp without time zone NOT NULL,
    fecha_final_publicacion timestamp without time zone NOT NULL,
    usuario_id bigint
);


ALTER TABLE public.evento OWNER TO postgres;

--
-- TOC entry 180 (class 1259 OID 20829)
-- Name: evento_patrocinador_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE evento_patrocinador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.evento_patrocinador_id_seq OWNER TO postgres;

--
-- TOC entry 2297 (class 0 OID 0)
-- Dependencies: 180
-- Name: SEQUENCE evento_patrocinador_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE evento_patrocinador_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 195 (class 1259 OID 20921)
-- Name: evento_patrocinador; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE evento_patrocinador (
    id bigint DEFAULT nextval('evento_patrocinador_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    evento_id bigint NOT NULL,
    patrocinador_id bigint NOT NULL
);


ALTER TABLE public.evento_patrocinador OWNER TO postgres;

--
-- TOC entry 181 (class 1259 OID 20831)
-- Name: localidad_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE localidad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.localidad_id_seq OWNER TO postgres;

--
-- TOC entry 2298 (class 0 OID 0)
-- Dependencies: 181
-- Name: SEQUENCE localidad_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE localidad_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 196 (class 1259 OID 20932)
-- Name: localidad; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE localidad (
    id bigint DEFAULT nextval('localidad_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(45) NOT NULL,
    localidad_id bigint
);


ALTER TABLE public.localidad OWNER TO postgres;

--
-- TOC entry 182 (class 1259 OID 20833)
-- Name: organizacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE organizacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.organizacion_id_seq OWNER TO postgres;

--
-- TOC entry 2299 (class 0 OID 0)
-- Dependencies: 182
-- Name: SEQUENCE organizacion_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE organizacion_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 197 (class 1259 OID 20941)
-- Name: organizacion; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE organizacion (
    id bigint DEFAULT nextval('organizacion_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(45) NOT NULL,
    direccion character varying(200) NOT NULL,
    telefono character varying(45) NOT NULL,
    fax character varying(45),
    correo character varying(100) NOT NULL,
    pagina_web character varying(100)
);


ALTER TABLE public.organizacion OWNER TO postgres;

--
-- TOC entry 183 (class 1259 OID 20835)
-- Name: patrocinador_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE patrocinador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.patrocinador_id_seq OWNER TO postgres;

--
-- TOC entry 2300 (class 0 OID 0)
-- Dependencies: 183
-- Name: SEQUENCE patrocinador_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE patrocinador_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 198 (class 1259 OID 20952)
-- Name: patrocinador; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE patrocinador (
    id bigint DEFAULT nextval('patrocinador_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(45) NOT NULL,
    telefono character varying(10),
    correo character varying(150) NOT NULL,
    direccion character varying(150)
);


ALTER TABLE public.patrocinador OWNER TO postgres;

--
-- TOC entry 172 (class 1259 OID 20813)
-- Name: pqrs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE pqrs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.pqrs_id_seq OWNER TO postgres;

--
-- TOC entry 2301 (class 0 OID 0)
-- Dependencies: 172
-- Name: SEQUENCE pqrs_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE pqrs_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 199 (class 1259 OID 20960)
-- Name: pqrs; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE pqrs (
    id bigint DEFAULT nextval('pqrs_id_seq'::regclass) NOT NULL,
    tipo_pqrs_id bigint NOT NULL,
    estado_pqrs_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    titulo character varying(50) NOT NULL,
    contenido character varying(2048) NOT NULL,
    usuario_id bigint
);


ALTER TABLE public.pqrs OWNER TO postgres;

--
-- TOC entry 184 (class 1259 OID 20837)
-- Name: recaudo_economico_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE recaudo_economico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.recaudo_economico_id_seq OWNER TO postgres;

--
-- TOC entry 2302 (class 0 OID 0)
-- Dependencies: 184
-- Name: SEQUENCE recaudo_economico_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE recaudo_economico_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 200 (class 1259 OID 20973)
-- Name: recaudo_economico; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE recaudo_economico (
    id bigint DEFAULT nextval('recaudo_economico_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    evento_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    observacion character varying(1024),
    tarifa_id bigint NOT NULL,
    valor_total bigint DEFAULT 0 NOT NULL,
    valor_parcial bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.recaudo_economico OWNER TO postgres;

--
-- TOC entry 173 (class 1259 OID 20815)
-- Name: recordar_me_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE recordar_me_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.recordar_me_id_seq OWNER TO postgres;

--
-- TOC entry 2303 (class 0 OID 0)
-- Dependencies: 173
-- Name: SEQUENCE recordar_me_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE recordar_me_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 209 (class 1259 OID 21200)
-- Name: recordar_me; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE recordar_me (
    id bigint DEFAULT nextval('recordar_me_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    ip_address character varying(50) NOT NULL,
    hash_cookie character varying(32) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.recordar_me OWNER TO postgres;

--
-- TOC entry 185 (class 1259 OID 20839)
-- Name: rol_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.rol_id_seq OWNER TO postgres;

--
-- TOC entry 2304 (class 0 OID 0)
-- Dependencies: 185
-- Name: SEQUENCE rol_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE rol_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 174 (class 1259 OID 20817)
-- Name: tarifa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE tarifa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.tarifa_id_seq OWNER TO postgres;

--
-- TOC entry 2305 (class 0 OID 0)
-- Dependencies: 174
-- Name: SEQUENCE tarifa_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE tarifa_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 201 (class 1259 OID 20997)
-- Name: tarifa; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tarifa (
    id bigint DEFAULT nextval('tarifa_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    descripcion character varying(1024) NOT NULL,
    valor bigint NOT NULL,
    actived boolean DEFAULT true NOT NULL
);


ALTER TABLE public.tarifa OWNER TO postgres;

--
-- TOC entry 2306 (class 0 OID 0)
-- Dependencies: 201
-- Name: COLUMN tarifa.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN tarifa.actived IS 'TRUE activado ; FALSE desactivado';


--
-- TOC entry 186 (class 1259 OID 20841)
-- Name: tipo_documento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE tipo_documento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.tipo_documento_id_seq OWNER TO postgres;

--
-- TOC entry 2307 (class 0 OID 0)
-- Dependencies: 186
-- Name: SEQUENCE tipo_documento_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE tipo_documento_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 202 (class 1259 OID 21009)
-- Name: tipo_documento; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_documento (
    id bigint DEFAULT nextval('tipo_documento_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(45) NOT NULL
);


ALTER TABLE public.tipo_documento OWNER TO postgres;

--
-- TOC entry 175 (class 1259 OID 20819)
-- Name: tipo_pqrs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE tipo_pqrs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.tipo_pqrs_id_seq OWNER TO postgres;

--
-- TOC entry 2308 (class 0 OID 0)
-- Dependencies: 175
-- Name: SEQUENCE tipo_pqrs_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE tipo_pqrs_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 203 (class 1259 OID 21017)
-- Name: tipo_pqrs; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_pqrs (
    id bigint DEFAULT nextval('tipo_pqrs_id_seq'::regclass) NOT NULL,
    nombre character varying(50) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


ALTER TABLE public.tipo_pqrs OWNER TO postgres;

--
-- TOC entry 2309 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN tipo_pqrs.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN tipo_pqrs.actived IS 'TRUE activado ; FALSE desactivado';


--
-- TOC entry 188 (class 1259 OID 20845)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.usuario_id_seq OWNER TO postgres;

--
-- TOC entry 2310 (class 0 OID 0)
-- Dependencies: 188
-- Name: SEQUENCE usuario_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 210 (class 1259 OID 21209)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE usuario (
    id bigint DEFAULT nextval('usuario_id_seq'::regclass) NOT NULL,
    user_name character varying(80) NOT NULL,
    password character varying(32) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    last_login_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 2311 (class 0 OID 0)
-- Dependencies: 210
-- Name: COLUMN usuario.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN usuario.actived IS 'TRUE = activado | FALSE = desactivado';


--
-- TOC entry 206 (class 1259 OID 21178)
-- Name: usuario_credencial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_credencial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.usuario_credencial_id_seq OWNER TO postgres;

--
-- TOC entry 2312 (class 0 OID 0)
-- Dependencies: 206
-- Name: SEQUENCE usuario_credencial_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_credencial_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 211 (class 1259 OID 21222)
-- Name: usuario_credencial; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE usuario_credencial (
    id bigint DEFAULT nextval('usuario_credencial_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    credencial_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.usuario_credencial OWNER TO postgres;

--
-- TOC entry 187 (class 1259 OID 20843)
-- Name: usuario_gusta_categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_gusta_categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.usuario_gusta_categoria_id_seq OWNER TO postgres;

--
-- TOC entry 2313 (class 0 OID 0)
-- Dependencies: 187
-- Name: SEQUENCE usuario_gusta_categoria_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_gusta_categoria_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 204 (class 1259 OID 21045)
-- Name: usuario_gusta_categoria; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE usuario_gusta_categoria (
    id bigint DEFAULT nextval('usuario_gusta_categoria_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    usuario_id bigint NOT NULL,
    categoria_id bigint NOT NULL
);


ALTER TABLE public.usuario_gusta_categoria OWNER TO postgres;

--
-- TOC entry 189 (class 1259 OID 20847)
-- Name: usuario_rol_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.usuario_rol_id_seq OWNER TO postgres;

--
-- TOC entry 2314 (class 0 OID 0)
-- Dependencies: 189
-- Name: SEQUENCE usuario_rol_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_rol_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 2140 (class 2606 OID 21189)
-- Name: pkbitacora; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY bitacora
    ADD CONSTRAINT pkbitacora PRIMARY KEY (id);


--
-- TOC entry 2093 (class 2606 OID 20864)
-- Name: pkcategoria; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY categoria
    ADD CONSTRAINT pkcategoria PRIMARY KEY (id);


--
-- TOC entry 2142 (class 2606 OID 21199)
-- Name: pkcredencial; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY credencial
    ADD CONSTRAINT pkcredencial PRIMARY KEY (id);


--
-- TOC entry 2098 (class 2606 OID 20880)
-- Name: pkdato_usuario; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY dato_usuario
    ADD CONSTRAINT pkdato_usuario PRIMARY KEY (id);


--
-- TOC entry 2100 (class 2606 OID 20895)
-- Name: pkdetalle_pqrs; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY detalle_pqrs
    ADD CONSTRAINT pkdetalle_pqrs PRIMARY KEY (id);


--
-- TOC entry 2102 (class 2606 OID 20906)
-- Name: pkestado_pqrs; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY estado_pqrs
    ADD CONSTRAINT pkestado_pqrs PRIMARY KEY (id);


--
-- TOC entry 2105 (class 2606 OID 20918)
-- Name: pkevento; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY evento
    ADD CONSTRAINT pkevento PRIMARY KEY (id);


--
-- TOC entry 2110 (class 2606 OID 20928)
-- Name: pkevento_patrocinador; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY evento_patrocinador
    ADD CONSTRAINT pkevento_patrocinador PRIMARY KEY (id);


--
-- TOC entry 2113 (class 2606 OID 20939)
-- Name: pklocalidad; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY localidad
    ADD CONSTRAINT pklocalidad PRIMARY KEY (id);


--
-- TOC entry 2115 (class 2606 OID 20951)
-- Name: pkorganizacion; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY organizacion
    ADD CONSTRAINT pkorganizacion PRIMARY KEY (id);


--
-- TOC entry 2117 (class 2606 OID 20959)
-- Name: pkpatrocinador; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY patrocinador
    ADD CONSTRAINT pkpatrocinador PRIMARY KEY (id);


--
-- TOC entry 2119 (class 2606 OID 20970)
-- Name: pkpqrs; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY pqrs
    ADD CONSTRAINT pkpqrs PRIMARY KEY (id);


--
-- TOC entry 2122 (class 2606 OID 20985)
-- Name: pkrecaudo_economico; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY recaudo_economico
    ADD CONSTRAINT pkrecaudo_economico PRIMARY KEY (id);


--
-- TOC entry 2144 (class 2606 OID 21206)
-- Name: pkrecordar_me; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY recordar_me
    ADD CONSTRAINT pkrecordar_me PRIMARY KEY (id);


--
-- TOC entry 2127 (class 2606 OID 21008)
-- Name: pktarifa; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tarifa
    ADD CONSTRAINT pktarifa PRIMARY KEY (id);


--
-- TOC entry 2129 (class 2606 OID 21016)
-- Name: pktipo_documento; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_documento
    ADD CONSTRAINT pktipo_documento PRIMARY KEY (id);


--
-- TOC entry 2131 (class 2606 OID 21025)
-- Name: pktipo_pqrs; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_pqrs
    ADD CONSTRAINT pktipo_pqrs PRIMARY KEY (id);


--
-- TOC entry 2148 (class 2606 OID 21217)
-- Name: pkusuario; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY usuario
    ADD CONSTRAINT pkusuario PRIMARY KEY (id);


--
-- TOC entry 2154 (class 2606 OID 21228)
-- Name: pkusuario_credencial; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT pkusuario_credencial PRIMARY KEY (id);


--
-- TOC entry 2133 (class 2606 OID 21052)
-- Name: pkusuario_gusta_categoria; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY usuario_gusta_categoria
    ADD CONSTRAINT pkusuario_gusta_categoria PRIMARY KEY (id);


--
-- TOC entry 2137 (class 1259 OID 21190)
-- Name: bitacora_fecha_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "bitacora_fecha_Idx" ON bitacora USING btree (fecha);


--
-- TOC entry 2138 (class 1259 OID 21191)
-- Name: bitacora_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "bitacora_usuario_id_Idx" ON bitacora USING btree (usuario_id);


--
-- TOC entry 2094 (class 1259 OID 20881)
-- Name: dato_usuario_localidad_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "dato_usuario_localidad_id_Idx" ON dato_usuario USING btree (localidad_id);


--
-- TOC entry 2095 (class 1259 OID 20882)
-- Name: dato_usuario_organizacion_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "dato_usuario_organizacion_id_Idx" ON dato_usuario USING btree (organizacion_id);


--
-- TOC entry 2096 (class 1259 OID 20883)
-- Name: dato_usuario_tipo_documento_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "dato_usuario_tipo_documento_id_Idx" ON dato_usuario USING btree (tipo_documento_id);


--
-- TOC entry 2106 (class 1259 OID 20929)
-- Name: evento_Patrocinador_evento_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "evento_Patrocinador_evento_id_Idx" ON evento_patrocinador USING btree (evento_id);


--
-- TOC entry 2107 (class 1259 OID 20930)
-- Name: evento_Patrocinador_evento_id_patrocinador_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "evento_Patrocinador_evento_id_patrocinador_id_Idx" ON evento_patrocinador USING btree (evento_id, patrocinador_id);


--
-- TOC entry 2108 (class 1259 OID 20931)
-- Name: evento_Patrocinador_patrocinador_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "evento_Patrocinador_patrocinador_id_Idx" ON evento_patrocinador USING btree (patrocinador_id);


--
-- TOC entry 2103 (class 1259 OID 20919)
-- Name: evento_categoria_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "evento_categoria_id_Idx" ON evento USING btree (categoria_id);


--
-- TOC entry 2111 (class 1259 OID 20940)
-- Name: localidad_localidad_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "localidad_localidad_id_Idx" ON localidad USING btree (localidad_id);


--
-- TOC entry 2120 (class 1259 OID 20971)
-- Name: pqrs_tipo_pqrs_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "pqrs_tipo_pqrs_id_Idx" ON pqrs USING btree (tipo_pqrs_id);


--
-- TOC entry 2123 (class 1259 OID 20986)
-- Name: recaudo_economico_evento_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "recaudo_economico_evento_id_Idx" ON recaudo_economico USING btree (evento_id);


--
-- TOC entry 2124 (class 1259 OID 20987)
-- Name: recaudo_economico_tarifa_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "recaudo_economico_tarifa_id_Idx" ON recaudo_economico USING btree (tarifa_id);


--
-- TOC entry 2125 (class 1259 OID 20988)
-- Name: recaudo_economico_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "recaudo_economico_usuario_id_Idx" ON recaudo_economico USING btree (usuario_id);


--
-- TOC entry 2145 (class 1259 OID 21207)
-- Name: recordar_me_ip_address_hash_cookie_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "recordar_me_ip_address_hash_cookie_Idx" ON recordar_me USING btree (ip_address, hash_cookie);


--
-- TOC entry 2146 (class 1259 OID 21208)
-- Name: recordar_me_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "recordar_me_usuario_id_Idx" ON recordar_me USING btree (usuario_id);


--
-- TOC entry 2149 (class 1259 OID 21218)
-- Name: usuario_actived_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_actived_Idx" ON usuario USING btree (actived);


--
-- TOC entry 2155 (class 1259 OID 21229)
-- Name: usuario_credencial_credencial_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_credencial_credencial_id_Idx" ON usuario_credencial USING btree (credencial_id);


--
-- TOC entry 2156 (class 1259 OID 21230)
-- Name: usuario_credencial_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_credencial_usuario_id_Idx" ON usuario_credencial USING btree (usuario_id);


--
-- TOC entry 2157 (class 1259 OID 21231)
-- Name: usuario_credencial_usuario_id_credencial_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "usuario_credencial_usuario_id_credencial_id_Idx" ON usuario_credencial USING btree (usuario_id, credencial_id);


--
-- TOC entry 2150 (class 1259 OID 21219)
-- Name: usuario_deleted_at_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_deleted_at_Idx" ON usuario USING btree (deleted_at);


--
-- TOC entry 2134 (class 1259 OID 21053)
-- Name: usuario_gusta_categoria_categoria_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_gusta_categoria_categoria_id_Idx" ON usuario_gusta_categoria USING btree (categoria_id);


--
-- TOC entry 2135 (class 1259 OID 21054)
-- Name: usuario_gusta_categoria_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_gusta_categoria_usuario_id_Idx" ON usuario_gusta_categoria USING btree (usuario_id);


--
-- TOC entry 2136 (class 1259 OID 21055)
-- Name: usuario_gusta_categoria_usuario_id_categoria_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "usuario_gusta_categoria_usuario_id_categoria_id_Idx" ON usuario_gusta_categoria USING btree (usuario_id, categoria_id);


--
-- TOC entry 2151 (class 1259 OID 21220)
-- Name: usuario_user_name_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "usuario_user_name_Idx" ON usuario USING btree (user_name);


--
-- TOC entry 2152 (class 1259 OID 21221)
-- Name: usuario_user_name_password_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_user_name_password_Idx" ON usuario USING btree (user_name, password);


--
-- TOC entry 2170 (class 2606 OID 21232)
-- Name: fk_bitacora_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY bitacora
    ADD CONSTRAINT fk_bitacora_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2158 (class 2606 OID 21061)
-- Name: fk_dato_usuario_localidad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY dato_usuario
    ADD CONSTRAINT fk_dato_usuario_localidad FOREIGN KEY (localidad_id) REFERENCES localidad(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2159 (class 2606 OID 21066)
-- Name: fk_dato_usuario_organizacion; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY dato_usuario
    ADD CONSTRAINT fk_dato_usuario_organizacion FOREIGN KEY (organizacion_id) REFERENCES organizacion(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2160 (class 2606 OID 21071)
-- Name: fk_dato_usuario_tipo_documento; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY dato_usuario
    ADD CONSTRAINT fk_dato_usuario_tipo_documento FOREIGN KEY (tipo_documento_id) REFERENCES tipo_documento(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2161 (class 2606 OID 21091)
-- Name: fk_evento_categoria; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY evento
    ADD CONSTRAINT fk_evento_categoria FOREIGN KEY (categoria_id) REFERENCES categoria(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2162 (class 2606 OID 21101)
-- Name: fk_evento_patrocinador_evento; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY evento_patrocinador
    ADD CONSTRAINT fk_evento_patrocinador_evento FOREIGN KEY (evento_id) REFERENCES evento(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2163 (class 2606 OID 21106)
-- Name: fk_evento_patrocinador_patrocinador; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY evento_patrocinador
    ADD CONSTRAINT fk_evento_patrocinador_patrocinador FOREIGN KEY (patrocinador_id) REFERENCES patrocinador(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2164 (class 2606 OID 21111)
-- Name: fk_localidad_localidad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY localidad
    ADD CONSTRAINT fk_localidad_localidad FOREIGN KEY (localidad_id) REFERENCES localidad(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2165 (class 2606 OID 21116)
-- Name: fk_pqrs_estado_pqrs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY pqrs
    ADD CONSTRAINT fk_pqrs_estado_pqrs FOREIGN KEY (estado_pqrs_id) REFERENCES estado_pqrs(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2166 (class 2606 OID 21121)
-- Name: fk_pqrs_tipo_pqrs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY pqrs
    ADD CONSTRAINT fk_pqrs_tipo_pqrs FOREIGN KEY (tipo_pqrs_id) REFERENCES tipo_pqrs(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2167 (class 2606 OID 21131)
-- Name: fk_recaudo_economico_evento; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY recaudo_economico
    ADD CONSTRAINT fk_recaudo_economico_evento FOREIGN KEY (evento_id) REFERENCES evento(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2168 (class 2606 OID 21136)
-- Name: fk_recaudo_economico_tarifa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY recaudo_economico
    ADD CONSTRAINT fk_recaudo_economico_tarifa FOREIGN KEY (tarifa_id) REFERENCES tarifa(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2171 (class 2606 OID 21237)
-- Name: fk_recordar_me_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY recordar_me
    ADD CONSTRAINT fk_recordar_me_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2172 (class 2606 OID 21242)
-- Name: fk_usuario_credencial_credencial; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_credencial_credencial FOREIGN KEY (credencial_id) REFERENCES credencial(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2173 (class 2606 OID 21247)
-- Name: fk_usuario_credencial_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_credencial_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2169 (class 2606 OID 21161)
-- Name: fk_usuario_gusta_categoria_categoria; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_gusta_categoria
    ADD CONSTRAINT fk_usuario_gusta_categoria_categoria FOREIGN KEY (categoria_id) REFERENCES categoria(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2286 (class 0 OID 0)
-- Dependencies: 5
-- Name: public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2015-05-04 09:43:11 COT

--
-- PostgreSQL database dump complete
--

-- ----------------------------
--  Records of "credencial"
-- ----------------------------
BEGIN;
INSERT INTO "credencial" (nombre) VALUES ('admin');
INSERT INTO "credencial" (nombre) VALUES ('usuario');
COMMIT;

-- ----------------------------
--  Records of "usuario" admin - 123
-- ----------------------------
BEGIN;
INSERT INTO "usuario" (user_name, password, actived, last_login_at) VALUES ('admin', '202cb962ac59075b964b07152d234b70', 't', null);
COMMIT;

-- ----------------------------
--  Records of "usuario_credencial"
-- ----------------------------
BEGIN;
INSERT INTO "usuario_credencial" (usuario_id, credencial_id) VALUES (1, 1);
COMMIT;	

-- ----------------------------
--  Records of "tipo_documento"
-- ----------------------------
BEGIN;
INSERT INTO "tipo_documento" (id, nombre) VALUES (1, 'Cedula De Ciudadania');
INSERT INTO "tipo_documento" (id, nombre) VALUES (2, 'extranjero');
COMMIT;	

-- ----------------------------
--  Records of "tipo_pqrs"
-- ----------------------------
BEGIN;
INSERT INTO "tipo_pqrs" (id, nombre) VALUES (1, 'queja');
INSERT INTO "tipo_pqrs" (id, nombre) VALUES (2, 'sugerencia');
COMMIT;	

-- ----------------------------
--  Records of "estado_pqrs"
-- ----------------------------
BEGIN;
INSERT INTO "estado_pqrs" (id, nombre) VALUES (1, 'recibido');
INSERT INTO "estado_pqrs" (id, nombre) VALUES (2, 'respondido');
COMMIT;	

-- ----------------------------
--  Records of "categoria"
-- ----------------------------
BEGIN;
INSERT INTO "categoria" (id, nombre) VALUES (1, 'baile');
INSERT INTO "categoria" (id, nombre) VALUES (2, 'musica');
COMMIT;	

-- ----------------------------
--  Records of "localidad"
-- ----------------------------
BEGIN;
INSERT INTO "localidad" (id, nombre) VALUES (1, 'cali');
INSERT INTO "localidad" (id, nombre) VALUES (2, 'bogota');
COMMIT;	

-- ----------------------------
--  Records of "organizacion"
-- ----------------------------
BEGIN;
INSERT INTO "organizacion" (id, nombre, direccion, telefono, fax, correo, pagina_web) VALUES (1, 'postobon', 'calle 5', 2345677, 456666, 'fghjhg@hjh.com', 'www.nnn.com');
INSERT INTO "organizacion" (id, nombre, direccion, telefono, fax, correo, pagina_web) VALUES (2, 'cocacola', 'calle 6', 0000000, 0000000, 'fghjhg@hjh.com', 'www.coco.com');
COMMIT;	